package codegen

const TmplCodeGeneratorPhrase = `// Code generated by codegen; DO NOT EDIT.
// This file was generated automatically and any changes will be overwritten.
`

const TmplLogicServiceFile = `package {{.ServiceNameToLower}}

import (
"context"
"errors"
"{{.PackageName}}/generated"
)

type Service struct {}

func NewService() *Service {
	return &Service{}
}
`

const TmplLogicServiceEndpoint = `
func (s *Service) {{.ServiceMethod}}(ctx context.Context, in *generated.{{.InputRequest}}) (*generated.{{.OutputResponse}}, error) {
var dest generated.{{.OutputResponse}}
return &dest, errors.New("not implemented")
}
`
